services:
  mysql:
    image: mysql:8.0
    container_name: mysql-employee
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE_FILE: /run/secrets/mysql_database
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend_net
    secrets:
      - mysql_root_password
      - mysql_database

  redis:
    image: redis:7.2
    container_name: redis
    command: ["redis-server"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data
    networks:
      - backend_net

  backend:
    image: its7prerna/backend:latest
    container_name: backend-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/employees
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD_FILE: /run/secrets/mysql_root_password
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - frontend_net
      - backend_net
    secrets:
      - mysql_root_password


  frontend:
    image: its7prerna/angular-frontend:latest
    container_name: angular-frontend
    ports:
      - "90:90"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - frontend_net

  docker-bench:
    image: docker/docker-bench-security
    container_name: docker-bench
    network_mode: host
    pid: host
    userns_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /usr/lib/systemd:/usr/lib/systemd:ro
      - /etc:/etc:ro
      - /lib/systemd:/lib/systemd:ro
      - /usr/bin/containerd:/usr/bin/containerd:ro
      # Mount a local folder to store reports
      - ./bench-reports:/reports
    command: ["sh", "-c", "./docker-bench-security.sh > /reports/docker-bench-report.txt 2>&1"] #1 stdout, 2 stderr; > redirect

volumes:
  mysql_data:
  redis_data:

networks:
  frontend_net:
  backend_net:

secrets:
  mysql_root_password:
    file: "/mnt/c/sw/mysql_root_password.txt"
  mysql_database:
    file: "/mnt/c/sw/mysql_database.txt"
